language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8

matrix:
  exclude:
    - python: "2.6"
        env: DJANGO=1.7
    - python: "2.6"
        env: DJANGO=1.8

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
  - pip install -r pip-test-req.txt
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 ."
  - pyflakes -x W .
script:
  - python runtests.py
